import { Movie } from './src/models/Movies.model';

export const movies: Movie[] = [
  {
    originalName: 'Parasite',
    englishName: 'Parasite',
    year: 2019,
    ratingFilmweb: 8.6,
    ratingImdb: 8.5,
  },
  {
    originalName: 'Léon',
    englishName: 'The Professional',
    year: 1994,
    ratingFilmweb: 8.8,
    ratingImdb: 8.5,
  },
  {
    originalName: 'La La Land',
    englishName: 'La La Land',
    year: 2016,
    ratingFilmweb: 7.8,
    ratingImdb: 8.0,
  },
  {
    originalName: 'Cidade de Deus',
    englishName: 'City of God',
    year: 2002,
    ratingFilmweb: 8.5,
    ratingImdb: 8.6,
  },
  {
    originalName: 'Forushande',
    englishName: 'The Salesman',
    year: 2016,
    ratingFilmweb: 7.6,
    ratingImdb: 7.8,
  },
  {
    originalName: 'Spirited Away',
    englishName: 'Spirited Away',
    year: 2001,
    ratingFilmweb: 8.6,
    ratingImdb: 8.6,
  },
  {
    originalName: 'Interstellar',
    englishName: 'Interstellar',
    year: 2014,
    ratingFilmweb: 8.6,
    ratingImdb: 8.7,
  },
  {
    originalName: 'Ширли-Мырли',
    englishName: 'What a Mess!',
    year: 1995,
    ratingFilmweb: 7.5,
    ratingImdb: 7.8,
  },
  {
    originalName: 'Der Untergang',
    englishName: 'Downfall',
    year: 2004,
    ratingFilmweb: 8.2,
    ratingImdb: 8.2,
  },
  {
    originalName: 'Il buono, il brutto, il cattivo',
    englishName: 'The Good, the Bad and the Ugly',
    year: 1966,
    ratingFilmweb: 8.8,
    ratingImdb: 8.8,
  },
  {
    originalName: 'Se7en',
    englishName: 'Se7en',
    year: 1995,
    ratingFilmweb: 8.5,
    ratingImdb: 8.6,
  },
  {
    originalName: 'The Dark Knight',
    englishName: 'The Dark Knight',
    year: 2008,
    ratingFilmweb: 9.0,
    ratingImdb: 9.0,
  },
  {
    originalName: 'Pulp Fiction',
    englishName: 'Pulp Fiction',
    year: 1994,
    ratingFilmweb: 8.8,
    ratingImdb: 8.9,
  },
  {
    originalName: 'Schindler\'s List',
    englishName: 'Schindler\'s List',
    year: 1993,
    ratingFilmweb: 9.0,
    ratingImdb: 9.0,
  },
  {
    originalName: 'The Shawshank Redemption',
    englishName: 'The Shawshank Redemption',
    year: 1994,
    ratingFilmweb: 9.1,
    ratingImdb: 9.3,
  },
  {
    originalName: 'Forrest Gump',
    englishName: 'Forrest Gump',
    year: 1994,
    ratingFilmweb: 8.8,
    ratingImdb: 8.8,
  },
  {
    originalName: 'Inception',
    englishName: 'Inception',
    year: 2010,
    ratingFilmweb: 8.7,
    ratingImdb: 8.8,
  },
  {
    originalName: 'Fight Club',
    englishName: 'Fight Club',
    year: 1999,
    ratingFilmweb: 8.8,
    ratingImdb: 8.8,
  },
  {
    originalName: 'The Matrix',
    englishName: 'The Matrix',
    year: 1999,
    ratingFilmweb: 8.6,
    ratingImdb: 8.7,
  },
  {
    originalName: 'The Godfather',
    englishName: 'The Godfather',
    year: 1972,
    ratingFilmweb: 9.0,
    ratingImdb: 9.2,
  },
];
