version: '3.9'

services:
  web:
    build:
       context: .
       dockerfile: ./docker/Dockerfile
    ports:
      - "5000:5000"
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: postgres:17.2-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env 
    ports:
      - "5432:5432"

volumes:
  postgres_data:
