version: '3.9'

services:
  web:
    build:
       context: .
       dockerfile: ./docker/Dockerfile
    ports:
      - "5000:5000"
    env_file:
      - .env
    volumes:
      - .:/app
    command: ["/scripts/application.sh"]
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:17.2-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env 
    ports:
      - "5432:5432"
    healthcheck:
      test: [ 'CMD-SHELL', 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}' ]
      interval: 2s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
